--======================================================
-- 회원 등급
--======================================================

CREATE TABLE MEMBER_GRADES (
    GRADE_NO NUMBER(10) NOT NULL,
    GRADE_CODE VARCHAR2(30) NOT NULL,
    GRADE_NAME VARCHAR2(50) NOT NULL,
    MIN_TOTAL_AMOUNT NUMBER(12) DEFAULT 0 NOT NULL,
    MIN_STAY_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    MILEAGE_RATE NUMBER(5,2) DEFAULT 0 NOT NULL,
    BENEFIT_DESC VARCHAR2(500),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    SORT_ORDER NUMBER(3) DEFAULT 1 NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL
);
ALTER TABLE MEMBER_GRADES ADD CONSTRAINT PK_MEMBER_GRADES PRIMARY KEY (GRADE_NO);

ALTER TABLE MEMBER_GRADES ADD CONSTRAINT UK_MEMBER_GRADES_CODE
    UNIQUE (GRADE_CODE);

ALTER TABLE MEMBER_GRADES ADD CONSTRAINT CK_MEMBER_GRADES_MIN_TOTAL_AMOUNT
    CHECK (MIN_TOTAL_AMOUNT >= 0);

ALTER TABLE MEMBER_GRADES ADD CONSTRAINT CK_MEMBER_GRADES_MIN_STAY_COUNT
    CHECK (MIN_STAY_COUNT >= 0);

ALTER TABLE MEMBER_GRADES ADD CONSTRAINT CK_MEMBER_GRADES_MILEAGE_RATE
    CHECK (MILEAGE_RATE >= 0);

ALTER TABLE MEMBER_GRADES ADD CONSTRAINT CK_MEMBER_GRADES_STATUS
    CHECK (STATUS IN ('ACTIVE', 'INACTIVE'));

ALTER TABLE MEMBER_GRADES ADD CONSTRAINT CK_MEMBER_GRADES_SORT_ORDER
    CHECK (SORT_ORDER > 0);
    
CREATE SEQUENCE SEQ_MEMBER_GRADES
START WITH 1
INCREMENT BY 1
NOCACHE;

COMMENT ON TABLE MEMBER_GRADES IS '회원 등급 정보 테이블';
COMMENT ON COLUMN MEMBER_GRADES.GRADE_NO IS '회원 등급 번호(PK)';
COMMENT ON COLUMN MEMBER_GRADES.GRADE_CODE IS '회원 등급 코드';
COMMENT ON COLUMN MEMBER_GRADES.GRADE_NAME IS '회원 등급명';
COMMENT ON COLUMN MEMBER_GRADES.MIN_TOTAL_AMOUNT IS '등급 최소 누적 결제 금액';
COMMENT ON COLUMN MEMBER_GRADES.MIN_STAY_COUNT IS '등급 최소 숙박 횟수';
COMMENT ON COLUMN MEMBER_GRADES.MILEAGE_RATE IS '마일리지 적립률';
COMMENT ON COLUMN MEMBER_GRADES.BENEFIT_DESC IS '등급 혜택 설명';
COMMENT ON COLUMN MEMBER_GRADES.STATUS IS '등급 상태';
COMMENT ON COLUMN MEMBER_GRADES.SORT_ORDER IS '등급 정렬 순서';
COMMENT ON COLUMN MEMBER_GRADES.REG_DATE IS '등록일';
COMMENT ON COLUMN MEMBER_GRADES.UPD_DATE IS '수정일';

--======================================================
-- 회원 
--======================================================

CREATE TABLE USERS (
    USER_NO NUMBER(10) NOT NULL,
    USER_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    GRADE_NO NUMBER(10),
    MILEAGE NUMBER(12) DEFAULT 0 NOT NULL,
    ENABLED CHAR(1) DEFAULT '1' NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL
);
ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (USER_NO);

ALTER TABLE USERS ADD CONSTRAINT UK_USERS_EMAIL
    UNIQUE (EMAIL);

ALTER TABLE USERS ADD CONSTRAINT FK_USERS_GRADE
    FOREIGN KEY (GRADE_NO) REFERENCES MEMBER_GRADES(GRADE_NO);

ALTER TABLE USERS ADD CONSTRAINT CK_USERS_ENABLED
    CHECK (ENABLED IN ('0', '1'));

ALTER TABLE USERS ADD CONSTRAINT CK_USERS_MILEAGE
    CHECK (MILEAGE >= 0);
    
CREATE SEQUENCE SEQ_USERS
START WITH 1
INCREMENT BY 1
NOCACHE;

COMMENT ON TABLE USERS IS '회원 기본 정보 테이블';
COMMENT ON COLUMN USERS.USER_NO IS '회원 번호(PK)';
COMMENT ON COLUMN USERS.USER_NAME IS '회원명';
COMMENT ON COLUMN USERS.EMAIL IS '이메일';
COMMENT ON COLUMN USERS.PHONE IS '전화번호';
COMMENT ON COLUMN USERS.GRADE_NO IS '회원 등급 번호(FK)';
COMMENT ON COLUMN USERS.MILEAGE IS '현재 보유 마일리지';
COMMENT ON COLUMN USERS.ENABLED IS '활성 여부';
COMMENT ON COLUMN USERS.REG_DATE IS '등록일';
COMMENT ON COLUMN USERS.UPD_DATE IS '수정일';

--======================================================
-- 회원 로그인 정보
--======================================================

CREATE TABLE USER_AUTH_PROVIDERS (
    USER_AUTH_NO NUMBER(10) NOT NULL,
    USER_NO NUMBER(10) NOT NULL,
    PROVIDER_CODE VARCHAR2(20) NOT NULL,
    PROVIDER_USER_ID VARCHAR2(200),
    LOGIN_ID VARCHAR2(100),
    PASSWORD_HASH VARCHAR2(255),
    CONNECTED_AT DATE DEFAULT SYSDATE NOT NULL,
    LAST_LOGIN_AT DATE,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE USER_AUTH_PROVIDERS ADD CONSTRAINT PK_USER_AUTH_PROVIDERS PRIMARY KEY (USER_AUTH_NO);
ALTER TABLE USER_AUTH_PROVIDERS ADD CONSTRAINT FK_USER_AUTH_PROVIDERS_USER FOREIGN KEY (USER_NO) 
    REFERENCES USERS(USER_NO);
ALTER TABLE USER_AUTH_PROVIDERS ADD CONSTRAINT UK_USER_AUTH_PROVIDER
    UNIQUE (USER_NO, PROVIDER_CODE);
ALTER TABLE USER_AUTH_PROVIDERS ADD CONSTRAINT UK_USER_AUTH_PROVIDER_USER
    UNIQUE (PROVIDER_CODE, PROVIDER_USER_ID);
ALTER TABLE USER_AUTH_PROVIDERS ADD CONSTRAINT UK_USER_AUTH_LOGIN_ID
    UNIQUE (LOGIN_ID);
ALTER TABLE USER_AUTH_PROVIDERS ADD CONSTRAINT CK_USER_AUTH_PROVIDER_CODE
    CHECK (PROVIDER_CODE IN ('LOCAL', 'GOOGLE', 'KAKAO', 'NAVER'));
    
    
CREATE SEQUENCE SEQ_USER_AUTH_PROVIDERS
START WITH 1
INCREMENT BY 1
NOCACHE;

COMMENT ON TABLE USER_AUTH_PROVIDERS IS '회원 인증 수단 정보 테이블';
COMMENT ON COLUMN USER_AUTH_PROVIDERS.USER_AUTH_NO IS '회원 인증 수단 번호(PK)';
COMMENT ON COLUMN USER_AUTH_PROVIDERS.USER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN USER_AUTH_PROVIDERS.PROVIDER_CODE IS '인증 제공자 코드(LOCAL, GOOGLE, KAKAO, NAVER)';
COMMENT ON COLUMN USER_AUTH_PROVIDERS.PROVIDER_USER_ID IS '소셜 로그인 제공자 회원 고유 ID';
COMMENT ON COLUMN USER_AUTH_PROVIDERS.LOGIN_ID IS '일반 로그인 ID';
COMMENT ON COLUMN USER_AUTH_PROVIDERS.PASSWORD_HASH IS '암호화된 비밀번호';
COMMENT ON COLUMN USER_AUTH_PROVIDERS.CONNECTED_AT IS '인증 수단 연결 일시';
COMMENT ON COLUMN USER_AUTH_PROVIDERS.LAST_LOGIN_AT IS '마지막 로그인 일시';
COMMENT ON COLUMN USER_AUTH_PROVIDERS.REG_DATE IS '등록일';
COMMENT ON COLUMN USER_AUTH_PROVIDERS.UPD_DATE IS '수정일';

--======================================================
-- 회원 권한
--======================================================

CREATE TABLE USER_ROLES (
    USER_ROLE_NO NUMBER(10) NOT NULL,
    USER_NO NUMBER(10) NOT NULL,
    ROLE_CODE VARCHAR2(30) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE USER_ROLES ADD CONSTRAINT PK_USER_ROLES PRIMARY KEY (USER_ROLE_NO);

ALTER TABLE USER_ROLES ADD CONSTRAINT FK_USER_ROLES_USER
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO);

ALTER TABLE USER_ROLES ADD CONSTRAINT UK_USER_ROLES_USER_ROLE
    UNIQUE (USER_NO, ROLE_CODE);

ALTER TABLE USER_ROLES ADD CONSTRAINT CK_USER_ROLES_ROLE_CODE
    CHECK (ROLE_CODE IN ('ROLE_USER', 'ROLE_HOST', 'ROLE_ADMIN'));
    
CREATE SEQUENCE SEQ_USER_ROLES
START WITH 1
INCREMENT BY 1
NOCACHE;

COMMENT ON TABLE USER_ROLES IS '회원 권한 정보 테이블';
COMMENT ON COLUMN USER_ROLES.USER_ROLE_NO IS '회원 권한 번호(PK)';
COMMENT ON COLUMN USER_ROLES.USER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN USER_ROLES.ROLE_CODE IS '권한 코드';
COMMENT ON COLUMN USER_ROLES.REG_DATE IS '등록일';

--======================================================
-- 판매자 정보
--======================================================

CREATE TABLE HOST_PROFILES (
    HOST_NO NUMBER(10) NOT NULL,
    USER_NO NUMBER(10) NOT NULL,
    BUSINESS_NAME VARCHAR2(100) NOT NULL,
    BUSINESS_NUMBER VARCHAR2(50) NOT NULL,
    OWNER_NAME VARCHAR2(100) NOT NULL,
    APPROVAL_STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    APPROVED_BY NUMBER(10),
    APPROVED_AT DATE,
    REJECT_REASON VARCHAR2(300),
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL
);
ALTER TABLE HOST_PROFILES ADD CONSTRAINT PK_HOST_PROFILES PRIMARY KEY (HOST_NO);

ALTER TABLE HOST_PROFILES ADD CONSTRAINT UK_HOST_PROFILES_USER
    UNIQUE (USER_NO);

ALTER TABLE HOST_PROFILES ADD CONSTRAINT UK_HOST_PROFILES_BUSINESS_NUMBER
    UNIQUE (BUSINESS_NUMBER);

ALTER TABLE HOST_PROFILES ADD CONSTRAINT FK_HOST_PROFILES_USER
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO);

ALTER TABLE HOST_PROFILES ADD CONSTRAINT FK_HOST_PROFILES_APPROVED_BY
    FOREIGN KEY (APPROVED_BY) REFERENCES USERS(USER_NO);

ALTER TABLE HOST_PROFILES ADD CONSTRAINT CK_HOST_PROFILES_APPROVAL_STATUS
    CHECK (APPROVAL_STATUS IN ('PENDING', 'APPROVED', 'REJECTED'));
    
CREATE SEQUENCE SEQ_HOST_PROFILES
START WITH 1
INCREMENT BY 1
NOCACHE;

COMMENT ON TABLE HOST_PROFILES IS '호스트 프로필 정보 테이블';
COMMENT ON COLUMN HOST_PROFILES.HOST_NO IS '호스트 번호(PK)';
COMMENT ON COLUMN HOST_PROFILES.USER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN HOST_PROFILES.BUSINESS_NAME IS '상호명';
COMMENT ON COLUMN HOST_PROFILES.BUSINESS_NUMBER IS '사업자등록번호';
COMMENT ON COLUMN HOST_PROFILES.OWNER_NAME IS '대표자명';
COMMENT ON COLUMN HOST_PROFILES.APPROVAL_STATUS IS '승인 상태';
COMMENT ON COLUMN HOST_PROFILES.APPROVED_BY IS '승인 처리한 관리자 회원 번호(FK)';
COMMENT ON COLUMN HOST_PROFILES.APPROVED_AT IS '승인 처리 일시';
COMMENT ON COLUMN HOST_PROFILES.REJECT_REASON IS '반려 사유';
COMMENT ON COLUMN HOST_PROFILES.REG_DATE IS '등록일';
COMMENT ON COLUMN HOST_PROFILES.UPD_DATE IS '수정일';

--======================================================
-- 이벤트
--======================================================

CREATE TABLE EVENTS (
    EVENT_NO NUMBER(10) NOT NULL,
    ADMIN_USER_NO NUMBER(10) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    THUMBNAIL_URL VARCHAR2(300),
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    EVENT_STATUS VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    VIEW_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE EVENTS ADD CONSTRAINT PK_EVENTS PRIMARY KEY (EVENT_NO);

ALTER TABLE EVENTS ADD CONSTRAINT FK_EVENTS_ADMIN
    FOREIGN KEY (ADMIN_USER_NO) REFERENCES USERS(USER_NO);

ALTER TABLE EVENTS ADD CONSTRAINT CK_EVENTS_DATE
    CHECK (END_DATE >= START_DATE);

ALTER TABLE EVENTS ADD CONSTRAINT CK_EVENTS_STATUS
    CHECK (EVENT_STATUS IN ('DRAFT', 'ONGOING', 'ENDED', 'HIDDEN'));

ALTER TABLE EVENTS ADD CONSTRAINT CK_EVENTS_VIEW_COUNT
    CHECK (VIEW_COUNT >= 0);
    
CREATE SEQUENCE SEQ_EVENTS
START WITH 1
INCREMENT BY 1
NOCACHE;

COMMENT ON TABLE EVENTS IS '이벤트 정보 테이블';
COMMENT ON COLUMN EVENTS.EVENT_NO IS '이벤트 번호(PK)';
COMMENT ON COLUMN EVENTS.ADMIN_USER_NO IS '등록 관리자 회원 번호(FK)';
COMMENT ON COLUMN EVENTS.TITLE IS '이벤트 제목';
COMMENT ON COLUMN EVENTS.CONTENT IS '이벤트 내용';
COMMENT ON COLUMN EVENTS.THUMBNAIL_URL IS '이벤트 썸네일 이미지 경로';
COMMENT ON COLUMN EVENTS.START_DATE IS '이벤트 시작일';
COMMENT ON COLUMN EVENTS.END_DATE IS '이벤트 종료일';
COMMENT ON COLUMN EVENTS.EVENT_STATUS IS '이벤트 상태';
COMMENT ON COLUMN EVENTS.VIEW_COUNT IS '조회수';
COMMENT ON COLUMN EVENTS.REG_DATE IS '등록일';
COMMENT ON COLUMN EVENTS.UPD_DATE IS '수정일';

--======================================================
-- 쿠폰
--======================================================

CREATE TABLE COUPONS (
    COUPON_NO NUMBER(10) NOT NULL,
    ISSUED_BY_USER_NO NUMBER(10) NOT NULL,
    COUPON_NAME VARCHAR2(100) NOT NULL,
    COUPON_CODE VARCHAR2(50) NOT NULL,
    DISCOUNT_TYPE VARCHAR2(20) NOT NULL,
    DISCOUNT_VALUE NUMBER(10) NOT NULL,
    MAX_DISCOUNT_AMOUNT NUMBER(10),
    MIN_ORDER_AMOUNT NUMBER(10) DEFAULT 0 NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE COUPONS ADD CONSTRAINT PK_COUPONS PRIMARY KEY (COUPON_NO);

ALTER TABLE COUPONS ADD CONSTRAINT UK_COUPONS_CODE
    UNIQUE (COUPON_CODE);

ALTER TABLE COUPONS ADD CONSTRAINT FK_COUPONS_ISSUED_BY_USER
    FOREIGN KEY (ISSUED_BY_USER_NO) REFERENCES USERS(USER_NO);

ALTER TABLE COUPONS ADD CONSTRAINT CK_COUPONS_DISCOUNT_TYPE
    CHECK (DISCOUNT_TYPE IN ('AMOUNT', 'PERCENT'));

ALTER TABLE COUPONS ADD CONSTRAINT CK_COUPONS_DISCOUNT_VALUE
    CHECK (DISCOUNT_VALUE > 0);

ALTER TABLE COUPONS ADD CONSTRAINT CK_COUPONS_MAX_DISCOUNT_AMOUNT
    CHECK (MAX_DISCOUNT_AMOUNT IS NULL OR MAX_DISCOUNT_AMOUNT >= 0);

ALTER TABLE COUPONS ADD CONSTRAINT CK_COUPONS_MIN_ORDER_AMOUNT
    CHECK (MIN_ORDER_AMOUNT >= 0);

ALTER TABLE COUPONS ADD CONSTRAINT CK_COUPONS_DATE
    CHECK (END_DATE >= START_DATE);

ALTER TABLE COUPONS ADD CONSTRAINT CK_COUPONS_STATUS
    CHECK (STATUS IN ('ACTIVE', 'INACTIVE'));
    
CREATE SEQUENCE SEQ_COUPONS
START WITH 1
INCREMENT BY 1
NOCACHE;

COMMENT ON TABLE COUPONS IS '쿠폰 마스터 정보 테이블';
COMMENT ON COLUMN COUPONS.COUPON_NO IS '쿠폰 번호(PK)';
COMMENT ON COLUMN COUPONS.ISSUED_BY_USER_NO IS '발급 관리자 회원 번호(FK)';
COMMENT ON COLUMN COUPONS.COUPON_NAME IS '쿠폰명';
COMMENT ON COLUMN COUPONS.COUPON_CODE IS '쿠폰 코드';
COMMENT ON COLUMN COUPONS.DISCOUNT_TYPE IS '할인 유형';
COMMENT ON COLUMN COUPONS.DISCOUNT_VALUE IS '할인 값';
COMMENT ON COLUMN COUPONS.MAX_DISCOUNT_AMOUNT IS '최대 할인 금액';
COMMENT ON COLUMN COUPONS.MIN_ORDER_AMOUNT IS '최소 주문 금액';
COMMENT ON COLUMN COUPONS.START_DATE IS '사용 시작일';
COMMENT ON COLUMN COUPONS.END_DATE IS '사용 종료일';
COMMENT ON COLUMN COUPONS.STATUS IS '쿠폰 상태';
COMMENT ON COLUMN COUPONS.REG_DATE IS '등록일';
COMMENT ON COLUMN COUPONS.UPD_DATE IS '수정일';

--======================================================
-- 숙소 정보
--======================================================

CREATE TABLE LODGINGS (
    LODGING_NO NUMBER(10) NOT NULL,
    HOST_NO NUMBER(10) NOT NULL,
    LODGING_NAME VARCHAR2(200) NOT NULL,
    LODGING_TYPE VARCHAR2(50) NOT NULL,
    REGION VARCHAR2(100) NOT NULL,
    ADDRESS VARCHAR2(300) NOT NULL,
    DETAIL_ADDRESS VARCHAR2(300),
    ZIP_CODE VARCHAR2(20),
    LATITUDE NUMBER(10,7),
    LONGITUDE NUMBER(10,7),
    DESCRIPTION VARCHAR2(2000),
    CHECK_IN_TIME VARCHAR2(20),
    CHECK_OUT_TIME VARCHAR2(20),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE LODGINGS ADD CONSTRAINT PK_LODGINGS PRIMARY KEY (LODGING_NO);

ALTER TABLE LODGINGS ADD CONSTRAINT FK_LODGINGS_HOST
    FOREIGN KEY (HOST_NO) REFERENCES HOST_PROFILES(HOST_NO);

ALTER TABLE LODGINGS ADD CONSTRAINT CK_LODGINGS_STATUS
    CHECK (STATUS IN ('ACTIVE', 'INACTIVE'));

ALTER TABLE LODGINGS ADD CONSTRAINT CK_LODGINGS_LATITUDE
    CHECK (LATITUDE IS NULL OR (LATITUDE BETWEEN -90 AND 90));

ALTER TABLE LODGINGS ADD CONSTRAINT CK_LODGINGS_LONGITUDE
    CHECK (LONGITUDE IS NULL OR (LONGITUDE BETWEEN -180 AND 180));
    
CREATE SEQUENCE SEQ_LODGINGS
START WITH 1
INCREMENT BY 1
NOCACHE;

COMMENT ON TABLE LODGINGS IS '숙소 기본 정보 테이블';
COMMENT ON COLUMN LODGINGS.LODGING_NO IS '숙소 번호(PK)';
COMMENT ON COLUMN LODGINGS.HOST_NO IS '호스트 번호(FK)';
COMMENT ON COLUMN LODGINGS.LODGING_NAME IS '숙소명';
COMMENT ON COLUMN LODGINGS.LODGING_TYPE IS '숙소 유형';
COMMENT ON COLUMN LODGINGS.REGION IS '지역';
COMMENT ON COLUMN LODGINGS.ADDRESS IS '기본 주소';
COMMENT ON COLUMN LODGINGS.DETAIL_ADDRESS IS '상세 주소';
COMMENT ON COLUMN LODGINGS.ZIP_CODE IS '우편번호';
COMMENT ON COLUMN LODGINGS.LATITUDE IS '위도';
COMMENT ON COLUMN LODGINGS.LONGITUDE IS '경도';
COMMENT ON COLUMN LODGINGS.DESCRIPTION IS '숙소 설명';
COMMENT ON COLUMN LODGINGS.CHECK_IN_TIME IS '체크인 시간';
COMMENT ON COLUMN LODGINGS.CHECK_OUT_TIME IS '체크아웃 시간';
COMMENT ON COLUMN LODGINGS.STATUS IS '숙소 상태';
COMMENT ON COLUMN LODGINGS.REG_DATE IS '등록일';
COMMENT ON COLUMN LODGINGS.UPD_DATE IS '수정일';

--======================================================
-- 방 정보
--======================================================

CREATE TABLE ROOMS (
    ROOM_NO NUMBER(10) NOT NULL,
    LODGING_NO NUMBER(10) NOT NULL,
    ROOM_NAME VARCHAR2(200) NOT NULL,
    ROOM_TYPE VARCHAR2(50) NOT NULL,
    ROOM_DESCRIPTION VARCHAR2(2000),
    MAX_GUEST_COUNT NUMBER(5) NOT NULL,
    PRICE_PER_NIGHT NUMBER(10) NOT NULL,
    ROOM_COUNT NUMBER(5) DEFAULT 1 NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE ROOMS ADD CONSTRAINT PK_ROOMS PRIMARY KEY (ROOM_NO);

ALTER TABLE ROOMS ADD CONSTRAINT FK_ROOMS_LODGING
    FOREIGN KEY (LODGING_NO) REFERENCES LODGINGS(LODGING_NO);

ALTER TABLE ROOMS ADD CONSTRAINT CK_ROOMS_MAX_GUEST_COUNT
    CHECK (MAX_GUEST_COUNT > 0);

ALTER TABLE ROOMS ADD CONSTRAINT CK_ROOMS_PRICE_PER_NIGHT
    CHECK (PRICE_PER_NIGHT >= 0);

ALTER TABLE ROOMS ADD CONSTRAINT CK_ROOMS_ROOM_COUNT
    CHECK (ROOM_COUNT > 0);

ALTER TABLE ROOMS ADD CONSTRAINT CK_ROOMS_STATUS
    CHECK (STATUS IN ('AVAILABLE', 'UNAVAILABLE'));
    
CREATE SEQUENCE SEQ_ROOMS
START WITH 1
INCREMENT BY 1
NOCACHE;

COMMENT ON TABLE ROOMS IS '객실 정보 테이블';
COMMENT ON COLUMN ROOMS.ROOM_NO IS '객실 번호(PK)';
COMMENT ON COLUMN ROOMS.LODGING_NO IS '숙소 번호(FK)';
COMMENT ON COLUMN ROOMS.ROOM_NAME IS '객실명';
COMMENT ON COLUMN ROOMS.ROOM_TYPE IS '객실 유형';
COMMENT ON COLUMN ROOMS.ROOM_DESCRIPTION IS '객실 설명';
COMMENT ON COLUMN ROOMS.MAX_GUEST_COUNT IS '최대 수용 인원';
COMMENT ON COLUMN ROOMS.PRICE_PER_NIGHT IS '1박 기준 가격';
COMMENT ON COLUMN ROOMS.ROOM_COUNT IS '동일 객실 수';
COMMENT ON COLUMN ROOMS.STATUS IS '객실 상태';
COMMENT ON COLUMN ROOMS.REG_DATE IS '등록일';
COMMENT ON COLUMN ROOMS.UPD_DATE IS '수정일';

--======================================================
-- 회원 쿠폰
--======================================================

CREATE TABLE USER_COUPONS (
    USER_COUPON_NO NUMBER(10) NOT NULL,
    USER_NO NUMBER(10) NOT NULL,
    COUPON_NO NUMBER(10) NOT NULL,
    ISSUED_AT DATE DEFAULT SYSDATE NOT NULL,
    USED_AT DATE,
    EXPIRED_AT DATE,
    STATUS VARCHAR2(20) DEFAULT 'ISSUED' NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE USER_COUPONS ADD CONSTRAINT PK_USER_COUPONS PRIMARY KEY (USER_COUPON_NO);

ALTER TABLE USER_COUPONS ADD CONSTRAINT FK_USER_COUPONS_USER
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO);

ALTER TABLE USER_COUPONS ADD CONSTRAINT FK_USER_COUPONS_COUPON
    FOREIGN KEY (COUPON_NO) REFERENCES COUPONS(COUPON_NO);

ALTER TABLE USER_COUPONS ADD CONSTRAINT CK_USER_COUPONS_STATUS
    CHECK (STATUS IN ('ISSUED', 'USED', 'EXPIRED', 'CANCELED'));
    
CREATE SEQUENCE SEQ_USER_COUPONS
START WITH 1
INCREMENT BY 1
NOCACHE;

COMMENT ON TABLE USER_COUPONS IS '회원 보유 쿠폰 테이블';
COMMENT ON COLUMN USER_COUPONS.USER_COUPON_NO IS '회원 쿠폰 번호(PK)';
COMMENT ON COLUMN USER_COUPONS.USER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN USER_COUPONS.COUPON_NO IS '쿠폰 번호(FK)';
COMMENT ON COLUMN USER_COUPONS.ISSUED_AT IS '발급 일시';
COMMENT ON COLUMN USER_COUPONS.USED_AT IS '사용 일시';
COMMENT ON COLUMN USER_COUPONS.EXPIRED_AT IS '만료 일시';
COMMENT ON COLUMN USER_COUPONS.STATUS IS '회원 쿠폰 상태';
COMMENT ON COLUMN USER_COUPONS.REG_DATE IS '등록일';
COMMENT ON COLUMN USER_COUPONS.UPD_DATE IS '수정일';

--======================================================
-- 이벤트 쿠폰
--======================================================

CREATE TABLE EVENT_COUPONS (
    EVENT_COUPON_NO NUMBER(10) NOT NULL,
    EVENT_NO NUMBER(10) NOT NULL,
    COUPON_NO NUMBER(10) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE EVENT_COUPONS ADD CONSTRAINT PK_EVENT_COUPONS PRIMARY KEY (EVENT_COUPON_NO);

ALTER TABLE EVENT_COUPONS ADD CONSTRAINT FK_EVENT_COUPONS_EVENT
    FOREIGN KEY (EVENT_NO) REFERENCES EVENTS(EVENT_NO);

ALTER TABLE EVENT_COUPONS ADD CONSTRAINT FK_EVENT_COUPONS_COUPON
    FOREIGN KEY (COUPON_NO) REFERENCES COUPONS(COUPON_NO);

ALTER TABLE EVENT_COUPONS ADD CONSTRAINT UK_EVENT_COUPONS_EVENT_COUPON
    UNIQUE (EVENT_NO, COUPON_NO);
    
CREATE SEQUENCE SEQ_EVENT_COUPONS
START WITH 1
INCREMENT BY 1
NOCACHE;

COMMENT ON TABLE EVENT_COUPONS IS '이벤트 쿠폰 연결 테이블';
COMMENT ON COLUMN EVENT_COUPONS.EVENT_COUPON_NO IS '이벤트 쿠폰 연결 번호(PK)';
COMMENT ON COLUMN EVENT_COUPONS.EVENT_NO IS '이벤트 번호(FK)';
COMMENT ON COLUMN EVENT_COUPONS.COUPON_NO IS '쿠폰 번호(FK)';
COMMENT ON COLUMN EVENT_COUPONS.REG_DATE IS '등록일';


--======================================================
-- 예약
--======================================================

CREATE TABLE BOOKINGS (
    BOOKING_NO NUMBER(10) NOT NULL,
    USER_NO NUMBER(10) NOT NULL,
    ROOM_NO NUMBER(10) NOT NULL,
    USER_COUPON_NO NUMBER(10),
    CHECK_IN_DATE DATE NOT NULL,
    CHECK_OUT_DATE DATE NOT NULL,
    GUEST_COUNT NUMBER(5) NOT NULL,
    PRICE_PER_NIGHT NUMBER(10) NOT NULL,
    DISCOUNT_AMOUNT NUMBER(10) DEFAULT 0 NOT NULL,
    TOTAL_PRICE NUMBER(10) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    REQUEST_MESSAGE VARCHAR2(500),
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE BOOKINGS ADD CONSTRAINT PK_BOOKINGS PRIMARY KEY (BOOKING_NO);

ALTER TABLE BOOKINGS ADD CONSTRAINT FK_BOOKINGS_USER
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO);

ALTER TABLE BOOKINGS ADD CONSTRAINT FK_BOOKINGS_ROOM
    FOREIGN KEY (ROOM_NO) REFERENCES ROOMS(ROOM_NO);

ALTER TABLE BOOKINGS ADD CONSTRAINT FK_BOOKINGS_USER_COUPON
    FOREIGN KEY (USER_COUPON_NO) REFERENCES USER_COUPONS(USER_COUPON_NO);

ALTER TABLE BOOKINGS ADD CONSTRAINT CK_BOOKINGS_GUEST_COUNT
    CHECK (GUEST_COUNT > 0);

ALTER TABLE BOOKINGS ADD CONSTRAINT CK_BOOKINGS_PRICE_PER_NIGHT
    CHECK (PRICE_PER_NIGHT >= 0);

ALTER TABLE BOOKINGS ADD CONSTRAINT CK_BOOKINGS_DISCOUNT_AMOUNT
    CHECK (DISCOUNT_AMOUNT >= 0);

ALTER TABLE BOOKINGS ADD CONSTRAINT CK_BOOKINGS_TOTAL_PRICE
    CHECK (TOTAL_PRICE >= 0);

ALTER TABLE BOOKINGS ADD CONSTRAINT CK_BOOKINGS_DATE
    CHECK (CHECK_OUT_DATE > CHECK_IN_DATE);

ALTER TABLE BOOKINGS ADD CONSTRAINT CK_BOOKINGS_STATUS
    CHECK (STATUS IN ('PENDING', 'CONFIRMED', 'CANCELED', 'COMPLETED'));
    
CREATE SEQUENCE SEQ_BOOKINGS
START WITH 1
INCREMENT BY 1
NOCACHE;

COMMENT ON TABLE BOOKINGS IS '예약 정보 테이블';
COMMENT ON COLUMN BOOKINGS.BOOKING_NO IS '예약 번호(PK)';
COMMENT ON COLUMN BOOKINGS.USER_NO IS '예약 회원 번호(FK)';
COMMENT ON COLUMN BOOKINGS.ROOM_NO IS '예약 객실 번호(FK)';
COMMENT ON COLUMN BOOKINGS.USER_COUPON_NO IS '사용 회원 쿠폰 번호(FK)';
COMMENT ON COLUMN BOOKINGS.CHECK_IN_DATE IS '체크인 날짜';
COMMENT ON COLUMN BOOKINGS.CHECK_OUT_DATE IS '체크아웃 날짜';
COMMENT ON COLUMN BOOKINGS.GUEST_COUNT IS '예약 인원';
COMMENT ON COLUMN BOOKINGS.PRICE_PER_NIGHT IS '예약 시점 1박 가격';
COMMENT ON COLUMN BOOKINGS.DISCOUNT_AMOUNT IS '할인 금액';
COMMENT ON COLUMN BOOKINGS.TOTAL_PRICE IS '총 결제 금액';
COMMENT ON COLUMN BOOKINGS.STATUS IS '예약 상태';
COMMENT ON COLUMN BOOKINGS.REQUEST_MESSAGE IS '요청사항';
COMMENT ON COLUMN BOOKINGS.REG_DATE IS '등록일';
COMMENT ON COLUMN BOOKINGS.UPD_DATE IS '수정일';

--======================================================
-- 결제
--======================================================

CREATE TABLE PAYMENTS (
    PAYMENT_NO NUMBER(10) NOT NULL,
    BOOKING_NO NUMBER(10) NOT NULL,
    PAYMENT_ID VARCHAR2(100) NOT NULL,
    STORE_ID VARCHAR2(100),
    CHANNEL_KEY VARCHAR2(200),
    ORDER_NAME VARCHAR2(200) NOT NULL,
    PAYMENT_AMOUNT NUMBER(10) NOT NULL,
    CURRENCY VARCHAR2(10) DEFAULT 'KRW' NOT NULL,
    PAY_METHOD VARCHAR2(30) NOT NULL,
    PG_PROVIDER VARCHAR2(30),
    PAYMENT_STATUS VARCHAR2(20) DEFAULT 'READY' NOT NULL,
    APPROVED_AT DATE,
    CANCELED_AT DATE,
    REFUND_AMOUNT NUMBER(10) DEFAULT 0 NOT NULL,
    FAIL_REASON VARCHAR2(500),
    RAW_RESPONSE CLOB,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE PAYMENTS ADD CONSTRAINT PK_PAYMENTS PRIMARY KEY (PAYMENT_NO);

ALTER TABLE PAYMENTS ADD CONSTRAINT FK_PAYMENTS_BOOKING
    FOREIGN KEY (BOOKING_NO) REFERENCES BOOKINGS(BOOKING_NO);

ALTER TABLE PAYMENTS ADD CONSTRAINT UK_PAYMENTS_BOOKING
    UNIQUE (BOOKING_NO);

ALTER TABLE PAYMENTS ADD CONSTRAINT UK_PAYMENTS_PAYMENT_ID
    UNIQUE (PAYMENT_ID);

ALTER TABLE PAYMENTS ADD CONSTRAINT CK_PAYMENTS_AMOUNT
    CHECK (PAYMENT_AMOUNT >= 0);

ALTER TABLE PAYMENTS ADD CONSTRAINT CK_PAYMENTS_REFUND_AMOUNT
    CHECK (REFUND_AMOUNT >= 0);

ALTER TABLE PAYMENTS ADD CONSTRAINT CK_PAYMENTS_CURRENCY
    CHECK (CURRENCY IN ('KRW'));

ALTER TABLE PAYMENTS ADD CONSTRAINT CK_PAYMENTS_PAY_METHOD
    CHECK (PAY_METHOD IN ('CARD', 'BANK_TRANSFER', 'VIRTUAL_ACCOUNT', 'MOBILE', 'EASY_PAY'));

ALTER TABLE PAYMENTS ADD CONSTRAINT CK_PAYMENTS_PAYMENT_STATUS
    CHECK (PAYMENT_STATUS IN ('READY', 'PAID', 'FAILED', 'CANCELED', 'PARTIAL_CANCELED', 'REFUNDED'));
    
CREATE SEQUENCE SEQ_PAYMENTS
START WITH 1
INCREMENT BY 1
NOCACHE;

COMMENT ON TABLE PAYMENTS IS '결제 정보 테이블';
COMMENT ON COLUMN PAYMENTS.PAYMENT_NO IS '결제 번호(PK)';
COMMENT ON COLUMN PAYMENTS.BOOKING_NO IS '예약 번호(FK)';
COMMENT ON COLUMN PAYMENTS.PAYMENT_ID IS '포트원 결제 식별값';
COMMENT ON COLUMN PAYMENTS.STORE_ID IS '포트원 스토어 ID';
COMMENT ON COLUMN PAYMENTS.CHANNEL_KEY IS '결제 채널 키';
COMMENT ON COLUMN PAYMENTS.ORDER_NAME IS '주문명';
COMMENT ON COLUMN PAYMENTS.PAYMENT_AMOUNT IS '결제 금액';
COMMENT ON COLUMN PAYMENTS.CURRENCY IS '통화 코드';
COMMENT ON COLUMN PAYMENTS.PAY_METHOD IS '결제 수단';
COMMENT ON COLUMN PAYMENTS.PG_PROVIDER IS 'PG 제공사';
COMMENT ON COLUMN PAYMENTS.PAYMENT_STATUS IS '결제 상태';
COMMENT ON COLUMN PAYMENTS.APPROVED_AT IS '결제 승인 일시';
COMMENT ON COLUMN PAYMENTS.CANCELED_AT IS '결제 취소 일시';
COMMENT ON COLUMN PAYMENTS.REFUND_AMOUNT IS '환불 금액';
COMMENT ON COLUMN PAYMENTS.FAIL_REASON IS '결제 실패 사유';
COMMENT ON COLUMN PAYMENTS.RAW_RESPONSE IS '결제 응답 원본 데이터';
COMMENT ON COLUMN PAYMENTS.REG_DATE IS '등록일';
COMMENT ON COLUMN PAYMENTS.UPD_DATE IS '수정일';


--======================================================
-- 숙소 이미지
--======================================================

CREATE TABLE LODGING_IMAGES (
    IMAGE_NO NUMBER(10) NOT NULL,
    LODGING_NO NUMBER(10) NOT NULL,
    IMAGE_URL VARCHAR2(300) NOT NULL,
    SORT_ORDER NUMBER(3) DEFAULT 1 NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE LODGING_IMAGES ADD CONSTRAINT PK_LODGING_IMAGES PRIMARY KEY (IMAGE_NO);

ALTER TABLE LODGING_IMAGES ADD CONSTRAINT FK_LODGING_IMAGES_LODGING
    FOREIGN KEY (LODGING_NO) REFERENCES LODGINGS(LODGING_NO);

ALTER TABLE LODGING_IMAGES ADD CONSTRAINT CK_LODGING_IMAGES_SORT_ORDER
    CHECK (SORT_ORDER > 0);
    
CREATE SEQUENCE SEQ_LODGING_IMAGES
START WITH 1
INCREMENT BY 1
NOCACHE;

COMMENT ON TABLE LODGING_IMAGES IS '숙소 이미지 정보 테이블';
COMMENT ON COLUMN LODGING_IMAGES.IMAGE_NO IS '숙소 이미지 번호(PK)';
COMMENT ON COLUMN LODGING_IMAGES.LODGING_NO IS '숙소 번호(FK)';
COMMENT ON COLUMN LODGING_IMAGES.IMAGE_URL IS '이미지 경로';
COMMENT ON COLUMN LODGING_IMAGES.SORT_ORDER IS '이미지 정렬 순서';
COMMENT ON COLUMN LODGING_IMAGES.REG_DATE IS '등록일';

--======================================================
-- 리뷰
--======================================================

CREATE TABLE REVIEWS (
    REVIEW_NO NUMBER(10) NOT NULL,
    BOOKING_NO NUMBER(10) NOT NULL,
    USER_NO NUMBER(10) NOT NULL,
    LODGING_NO NUMBER(10) NOT NULL,
    RATING NUMBER(2) NOT NULL,
    CONTENT VARCHAR2(1000) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE REVIEWS ADD CONSTRAINT PK_REVIEWS PRIMARY KEY (REVIEW_NO);

ALTER TABLE REVIEWS ADD CONSTRAINT FK_REVIEWS_BOOKING
    FOREIGN KEY (BOOKING_NO) REFERENCES BOOKINGS(BOOKING_NO);

ALTER TABLE REVIEWS ADD CONSTRAINT FK_REVIEWS_USER
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO);

ALTER TABLE REVIEWS ADD CONSTRAINT FK_REVIEWS_LODGING
    FOREIGN KEY (LODGING_NO) REFERENCES LODGINGS(LODGING_NO);

ALTER TABLE REVIEWS ADD CONSTRAINT UK_REVIEWS_BOOKING
    UNIQUE (BOOKING_NO);

ALTER TABLE REVIEWS ADD CONSTRAINT CK_REVIEWS_RATING
    CHECK (RATING BETWEEN 1 AND 5);
    
CREATE SEQUENCE SEQ_REVIEWS
START WITH 1
INCREMENT BY 1
NOCACHE;

COMMENT ON TABLE REVIEWS IS '리뷰 정보 테이블';
COMMENT ON COLUMN REVIEWS.REVIEW_NO IS '리뷰 번호(PK)';
COMMENT ON COLUMN REVIEWS.BOOKING_NO IS '예약 번호(FK)';
COMMENT ON COLUMN REVIEWS.USER_NO IS '작성 회원 번호(FK)';
COMMENT ON COLUMN REVIEWS.LODGING_NO IS '숙소 번호(FK)';
COMMENT ON COLUMN REVIEWS.RATING IS '평점';
COMMENT ON COLUMN REVIEWS.CONTENT IS '리뷰 내용';
COMMENT ON COLUMN REVIEWS.REG_DATE IS '등록일';
COMMENT ON COLUMN REVIEWS.UPD_DATE IS '수정일';


--======================================================
-- 리뷰이미지
--======================================================


CREATE TABLE REVIEW_IMAGES (
    REVIEW_IMAGE_NO NUMBER(10) NOT NULL,
    REVIEW_NO NUMBER(10) NOT NULL,
    IMAGE_URL VARCHAR2(300) NOT NULL,
    SORT_ORDER NUMBER(3) DEFAULT 1 NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE REVIEW_IMAGES ADD CONSTRAINT PK_REVIEW_IMAGES PRIMARY KEY (REVIEW_IMAGE_NO);

ALTER TABLE REVIEW_IMAGES ADD CONSTRAINT FK_REVIEW_IMAGES_REVIEW
    FOREIGN KEY (REVIEW_NO) REFERENCES REVIEWS(REVIEW_NO);

ALTER TABLE REVIEW_IMAGES ADD CONSTRAINT CK_REVIEW_IMAGES_SORT_ORDER
    CHECK (SORT_ORDER > 0);
    
CREATE SEQUENCE SEQ_REVIEW_IMAGES
START WITH 1
INCREMENT BY 1
NOCACHE;

COMMENT ON TABLE REVIEW_IMAGES IS '리뷰 이미지 정보 테이블';
COMMENT ON COLUMN REVIEW_IMAGES.REVIEW_IMAGE_NO IS '리뷰 이미지 번호(PK)';
COMMENT ON COLUMN REVIEW_IMAGES.REVIEW_NO IS '리뷰 번호(FK)';
COMMENT ON COLUMN REVIEW_IMAGES.IMAGE_URL IS '이미지 경로';
COMMENT ON COLUMN REVIEW_IMAGES.SORT_ORDER IS '이미지 정렬 순서';
COMMENT ON COLUMN REVIEW_IMAGES.REG_DATE IS '등록일';

--======================================================
-- 위시리스트
--======================================================

CREATE TABLE WISHLISTS (
    WISHLIST_NO NUMBER(10) NOT NULL,
    USER_NO NUMBER(10) NOT NULL,
    LODGING_NO NUMBER(10) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE WISHLISTS ADD CONSTRAINT PK_WISHLISTS PRIMARY KEY (WISHLIST_NO);

ALTER TABLE WISHLISTS ADD CONSTRAINT FK_WISHLISTS_USER
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO);

ALTER TABLE WISHLISTS ADD CONSTRAINT FK_WISHLISTS_LODGING
    FOREIGN KEY (LODGING_NO) REFERENCES LODGINGS(LODGING_NO);

ALTER TABLE WISHLISTS ADD CONSTRAINT UK_WISHLISTS_USER_LODGING
    UNIQUE (USER_NO, LODGING_NO);
    
CREATE SEQUENCE SEQ_WISHLISTS
START WITH 1
INCREMENT BY 1
NOCACHE;

COMMENT ON TABLE WISHLISTS IS '회원 찜 정보 테이블';
COMMENT ON COLUMN WISHLISTS.WISHLIST_NO IS '찜 번호(PK)';
COMMENT ON COLUMN WISHLISTS.USER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN WISHLISTS.LODGING_NO IS '숙소 번호(FK)';
COMMENT ON COLUMN WISHLISTS.REG_DATE IS '등록일';

--======================================================
-- 마일리지
--======================================================

CREATE TABLE MILEAGE_HISTORY (
    MILEAGE_HISTORY_NO NUMBER(10) NOT NULL,
    USER_NO NUMBER(10) NOT NULL,
    BOOKING_NO NUMBER(10),
    PAYMENT_NO NUMBER(10),
    CHANGE_TYPE VARCHAR2(20) NOT NULL,
    CHANGE_AMOUNT NUMBER(12) NOT NULL,
    BALANCE_AFTER NUMBER(12) NOT NULL,
    REASON VARCHAR2(200) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'NORMAL' NOT NULL,
    EXPIRED_AT DATE,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE MILEAGE_HISTORY ADD CONSTRAINT PK_MILEAGE_HISTORY PRIMARY KEY (MILEAGE_HISTORY_NO);

ALTER TABLE MILEAGE_HISTORY ADD CONSTRAINT FK_MILEAGE_HISTORY_USER
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO);

ALTER TABLE MILEAGE_HISTORY ADD CONSTRAINT FK_MILEAGE_HISTORY_BOOKING
    FOREIGN KEY (BOOKING_NO) REFERENCES BOOKINGS(BOOKING_NO);

ALTER TABLE MILEAGE_HISTORY ADD CONSTRAINT FK_MILEAGE_HISTORY_PAYMENT
    FOREIGN KEY (PAYMENT_NO) REFERENCES PAYMENTS(PAYMENT_NO);

ALTER TABLE MILEAGE_HISTORY ADD CONSTRAINT CK_MILEAGE_HISTORY_CHANGE_TYPE
    CHECK (CHANGE_TYPE IN ('EARN', 'USE', 'CANCEL_USE', 'EXPIRE', 'ADJUST'));

ALTER TABLE MILEAGE_HISTORY ADD CONSTRAINT CK_MILEAGE_HISTORY_CHANGE_AMOUNT
    CHECK (CHANGE_AMOUNT <> 0);

ALTER TABLE MILEAGE_HISTORY ADD CONSTRAINT CK_MILEAGE_HISTORY_BALANCE_AFTER
    CHECK (BALANCE_AFTER >= 0);

ALTER TABLE MILEAGE_HISTORY ADD CONSTRAINT CK_MILEAGE_HISTORY_STATUS
    CHECK (STATUS IN ('NORMAL', 'CANCELED'));

CREATE SEQUENCE SEQ_MILEAGE_HISTORY
START WITH 1
INCREMENT BY 1
NOCACHE;

COMMENT ON TABLE MILEAGE_HISTORY IS '마일리지 변동 이력 테이블';
COMMENT ON COLUMN MILEAGE_HISTORY.MILEAGE_HISTORY_NO IS '마일리지 이력 번호(PK)';
COMMENT ON COLUMN MILEAGE_HISTORY.USER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN MILEAGE_HISTORY.BOOKING_NO IS '예약 번호(FK)';
COMMENT ON COLUMN MILEAGE_HISTORY.PAYMENT_NO IS '결제 번호(FK)';
COMMENT ON COLUMN MILEAGE_HISTORY.CHANGE_TYPE IS '마일리지 변동 유형';
COMMENT ON COLUMN MILEAGE_HISTORY.CHANGE_AMOUNT IS '변동 금액';
COMMENT ON COLUMN MILEAGE_HISTORY.BALANCE_AFTER IS '변동 후 잔액';
COMMENT ON COLUMN MILEAGE_HISTORY.REASON IS '변동 사유';
COMMENT ON COLUMN MILEAGE_HISTORY.STATUS IS '이력 상태';
COMMENT ON COLUMN MILEAGE_HISTORY.EXPIRED_AT IS '만료 일시';
COMMENT ON COLUMN MILEAGE_HISTORY.REG_DATE IS '등록일';
COMMENT ON COLUMN MILEAGE_HISTORY.UPD_DATE IS '수정일';

--======================================================
-- 문의방
--======================================================

CREATE TABLE INQUIRY_ROOMS (
    INQUIRY_ROOM_NO NUMBER(10) NOT NULL,
    USER_NO NUMBER(10) NOT NULL,
    TARGET_TYPE VARCHAR2(20) NOT NULL,
    INQUIRY_TYPE VARCHAR2(30) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    ADMIN_USER_NO NUMBER(10),
    LODGING_NO NUMBER(10),
    STATUS VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
    LAST_MESSAGE_AT DATE,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE INQUIRY_ROOMS ADD CONSTRAINT PK_INQUIRY_ROOMS PRIMARY KEY (INQUIRY_ROOM_NO);

ALTER TABLE INQUIRY_ROOMS ADD CONSTRAINT FK_INQUIRY_ROOMS_USER
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO);

ALTER TABLE INQUIRY_ROOMS ADD CONSTRAINT FK_INQUIRY_ROOMS_ADMIN
    FOREIGN KEY (ADMIN_USER_NO) REFERENCES USERS(USER_NO);

ALTER TABLE INQUIRY_ROOMS ADD CONSTRAINT FK_INQUIRY_ROOMS_LODGING
    FOREIGN KEY (LODGING_NO) REFERENCES LODGINGS(LODGING_NO);

ALTER TABLE INQUIRY_ROOMS ADD CONSTRAINT CK_INQUIRY_ROOMS_TARGET_TYPE
    CHECK (TARGET_TYPE IN ('ADMIN', 'HOST'));

ALTER TABLE INQUIRY_ROOMS ADD CONSTRAINT CK_INQUIRY_ROOMS_INQUIRY_TYPE
    CHECK (INQUIRY_TYPE IN ('GENERAL', 'HOST_APPLY', 'LODGING', 'BOOKING', 'PAYMENT', 'ETC'));

ALTER TABLE INQUIRY_ROOMS ADD CONSTRAINT CK_INQUIRY_ROOMS_STATUS
    CHECK (STATUS IN ('OPEN', 'WAITING', 'ANSWERED', 'CLOSED'));

CREATE SEQUENCE SEQ_INQUIRY_ROOMS
START WITH 1
INCREMENT BY 1
NOCACHE;

COMMENT ON TABLE INQUIRY_ROOMS IS '문의방 정보 테이블';
COMMENT ON COLUMN INQUIRY_ROOMS.INQUIRY_ROOM_NO IS '문의방 번호(PK)';
COMMENT ON COLUMN INQUIRY_ROOMS.USER_NO IS '문의 작성 회원 번호(FK)';
COMMENT ON COLUMN INQUIRY_ROOMS.TARGET_TYPE IS '문의 대상 유형';
COMMENT ON COLUMN INQUIRY_ROOMS.INQUIRY_TYPE IS '문의 유형';
COMMENT ON COLUMN INQUIRY_ROOMS.TITLE IS '문의 제목';
COMMENT ON COLUMN INQUIRY_ROOMS.ADMIN_USER_NO IS '담당 관리자 회원 번호(FK)';
COMMENT ON COLUMN INQUIRY_ROOMS.LODGING_NO IS '관련 숙소 번호(FK)';
COMMENT ON COLUMN INQUIRY_ROOMS.STATUS IS '문의방 상태';
COMMENT ON COLUMN INQUIRY_ROOMS.LAST_MESSAGE_AT IS '마지막 메시지 일시';
COMMENT ON COLUMN INQUIRY_ROOMS.REG_DATE IS '등록일';
COMMENT ON COLUMN INQUIRY_ROOMS.UPD_DATE IS '수정일';

--======================================================
-- 문의메세지
--======================================================

CREATE TABLE INQUIRY_MESSAGES (
    MESSAGE_NO NUMBER(10) NOT NULL,
    INQUIRY_ROOM_NO NUMBER(10) NOT NULL,
    SENDER_USER_NO NUMBER(10) NOT NULL,
    SENDER_TYPE VARCHAR2(20) NOT NULL,
    MESSAGE_CONTENT VARCHAR2(2000),
    IMAGE_URL VARCHAR2(300),
    READ_YN CHAR(1) DEFAULT '0' NOT NULL,
    READ_AT DATE,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE INQUIRY_MESSAGES ADD CONSTRAINT PK_INQUIRY_MESSAGES PRIMARY KEY (MESSAGE_NO);

ALTER TABLE INQUIRY_MESSAGES ADD CONSTRAINT FK_INQUIRY_MESSAGES_ROOM
    FOREIGN KEY (INQUIRY_ROOM_NO) REFERENCES INQUIRY_ROOMS(INQUIRY_ROOM_NO);

ALTER TABLE INQUIRY_MESSAGES ADD CONSTRAINT FK_INQUIRY_MESSAGES_SENDER
    FOREIGN KEY (SENDER_USER_NO) REFERENCES USERS(USER_NO);

ALTER TABLE INQUIRY_MESSAGES ADD CONSTRAINT CK_INQUIRY_MESSAGES_SENDER_TYPE
    CHECK (SENDER_TYPE IN ('USER', 'ADMIN', 'HOST', 'SYSTEM'));

ALTER TABLE INQUIRY_MESSAGES ADD CONSTRAINT CK_INQUIRY_MESSAGES_READ_YN
    CHECK (READ_YN IN ('0', '1'));

ALTER TABLE INQUIRY_MESSAGES ADD CONSTRAINT CK_INQUIRY_MESSAGES_CONTENT
    CHECK (MESSAGE_CONTENT IS NOT NULL OR IMAGE_URL IS NOT NULL);

CREATE SEQUENCE SEQ_INQUIRY_MESSAGES
START WITH 1
INCREMENT BY 1
NOCACHE;

COMMENT ON TABLE INQUIRY_MESSAGES IS '문의 메시지 정보 테이블';
COMMENT ON COLUMN INQUIRY_MESSAGES.MESSAGE_NO IS '문의 메시지 번호(PK)';
COMMENT ON COLUMN INQUIRY_MESSAGES.INQUIRY_ROOM_NO IS '문의방 번호(FK)';
COMMENT ON COLUMN INQUIRY_MESSAGES.SENDER_USER_NO IS '발신 회원 번호(FK)';
COMMENT ON COLUMN INQUIRY_MESSAGES.SENDER_TYPE IS '발신자 유형';
COMMENT ON COLUMN INQUIRY_MESSAGES.MESSAGE_CONTENT IS '메시지 내용';
COMMENT ON COLUMN INQUIRY_MESSAGES.IMAGE_URL IS '첨부 이미지 경로';
COMMENT ON COLUMN INQUIRY_MESSAGES.READ_YN IS '읽음 여부';
COMMENT ON COLUMN INQUIRY_MESSAGES.READ_AT IS '읽은 일시';
COMMENT ON COLUMN INQUIRY_MESSAGES.REG_DATE IS '등록일';
COMMENT ON COLUMN INQUIRY_MESSAGES.UPD_DATE IS '수정일';

--======================================================
--  리프레시 토큰 정보 테이블
--======================================================

CREATE TABLE USER_REFRESH_TOKENS (
    REFRESH_TOKEN_NO NUMBER(10) NOT NULL,
    USER_NO NUMBER(10) NOT NULL,
    TOKEN_VALUE VARCHAR2(500) NOT NULL,
    EXPIRES_AT DATE NOT NULL,
    REVOKED_YN CHAR(1) DEFAULT '0' NOT NULL,
    REVOKED_AT DATE,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_DATE DATE DEFAULT SYSDATE NOT NULL
);
ALTER TABLE USER_REFRESH_TOKENS ADD CONSTRAINT PK_USER_REFRESH_TOKENS PRIMARY KEY (REFRESH_TOKEN_NO);

ALTER TABLE USER_REFRESH_TOKENS ADD CONSTRAINT FK_USER_REFRESH_TOKENS_USER
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO);

ALTER TABLE USER_REFRESH_TOKENS ADD CONSTRAINT UK_USER_REFRESH_TOKENS_TOKEN_VALUE
    UNIQUE (TOKEN_VALUE);

ALTER TABLE USER_REFRESH_TOKENS ADD CONSTRAINT CK_USER_REFRESH_TOKENS_REVOKED_YN
    CHECK (REVOKED_YN IN ('0', '1'));

CREATE SEQUENCE SEQ_USER_REFRESH_TOKENS
START WITH 1
INCREMENT BY 1
NOCACHE;

COMMENT ON TABLE USER_REFRESH_TOKENS IS '회원 리프레시 토큰 정보 테이블';
COMMENT ON COLUMN USER_REFRESH_TOKENS.REFRESH_TOKEN_NO IS '리프레시 토큰 번호(PK)';
COMMENT ON COLUMN USER_REFRESH_TOKENS.USER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN USER_REFRESH_TOKENS.TOKEN_VALUE IS '리프레시 토큰 값';
COMMENT ON COLUMN USER_REFRESH_TOKENS.EXPIRES_AT IS '토큰 만료 일시';
COMMENT ON COLUMN USER_REFRESH_TOKENS.REVOKED_YN IS '폐기 여부';
COMMENT ON COLUMN USER_REFRESH_TOKENS.REVOKED_AT IS '폐기 일시';
COMMENT ON COLUMN USER_REFRESH_TOKENS.REG_DATE IS '등록일';
COMMENT ON COLUMN USER_REFRESH_TOKENS.UPD_DATE IS '수정일';
