spring.application.name=TripZoneProject

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=SH
spring.datasource.password=SH

spring.jpa.database=oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.id.new_generator_mappings=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
logging.level.org.hibernate=info

# JWT secret key
jwt.secret=sdkfjsiejfhxhciocoianeisofienahffjeisinOEiffndi

# access token expiration time (seconds)
jwt.access-token-expiration=600

# refresh token expiration time (seconds)
jwt.refresh-token-expiration=1209600

# security log
logging.level.org.springframework.security=trace